#!/bin/sh

# A simple pre-commit hook that makes it illegal to commit to master
# on the webapp repo.  An exception is made for the automated process
# which is the only thing allowed to merge into master.
#
# For emergencies, you can override this hook by using 'git commit -n'.


# If you want to restrict other repos, just add another "-e <name>".
REPOS="-e Khan/webapp"

# If you want to whitelist other users, just add another "-e <email>".
SUPERUSERS="-e jenkins@khanacademy.org"


if ! git remote -v | grep -w $REPOS >/dev/null; then
    exit 0
fi

if git config --get user.email | grep -x $SUPERUSERS >/dev/null; then
    exit 0
fi

if [ "`git rev-parse --abbrev-ref HEAD`" = "master" ]; then
   echo "FATAL ERROR: You cannot commit directly to the master branch."
   echo "Commit to a deploy branch instead:"
   echo "https://sites.google.com/a/khanacademy.org/forge/for-developers/working-with-git-and-mercurial/git-at-ka"
   exit 1
fi
