#!/bin/sh

# A simple pre-push hook (git 1.8.2 or higher) that makes it illegal
# to push to master on the remote.  An exception is made for the
# automated process which is the only thing allowed to merge into
# master and then push it to github.  For emergencies, you can
# override this hook by using 'git push --no-verify'.

# IF YOU UPDATE THESE VARS, be sure to update no-commit-to-master as well.

# If you want to restrict other repos, just add another "-e <name>".
REPOS="-e Khan/webapp"

# If you want to whitelist other users, just add another "-e <email>".
SUPERUSERS="-e jenkins@khanacademy.org"


if ! git remote -v | grep -w $REPOS >/dev/null; then
    exit 0
fi

if git config --get user.email | grep -x $SUPERUSERS >/dev/null; then
    exit 0
fi

# Each line has the format
#    <local ref> <sha> <remote ref> <sha>
# We complain if any remote ref is refs/heads/master
while read local_ref local_sha remote_ref remote_sha; do
    if [ "$remote_ref" = "refs/heads/master" ]; then
        echo "FATAL ERROR: You cannot push to the master branch on github."
        echo "Instead, you must deploy a deploy-branch via Jenkins:"
        echo "    https://sites.google.com/a/khanacademy.org/forge/for-developers/working-with-git-and-mercurial/git-at-ka"
        exit 1
    fi
done
