# -*- mode: ruby -*-
# vi: set ft=ruby :

# See Load Order and Merging in vagrant documentation:
#   https://www.vagrantup.com/docs/vagrantfile

Vagrant.configure("2") do |config|
  # TODO(ericbrown): Verify shared folders this way don't have performance issues
  # Share users ~/khan to VM: (multiple shares are possible)
  #   Share an additional folder to the guest VM. The first argument is
  #   the path on the host to the actual folder. The second argument is
  #   the path on the guest to mount the folder. And the optional third
  #   argument is a set of non-required options.
  config.vm.synced_folder "~/khan", "/home/vagrant/khan"

  # TODO(ericbrown): Port mapping (not working - needs investigation)
  #config.vm.network "forwarded_port", guest: 2000, host: 12000, auto_correct: true
  #config.vm.network "forwarded_port", guest: 8000, host: 18000, auto_correct: true
  #config.vm.network "forwarded_port", guest: 8001, host: 18001, auto_correct: true
  #config.vm.network "forwarded_port", guest: 8080, host: 18080, auto_correct: true
  #config.vm.network "forwarded_port", guest: 8088, host: 18888, auto_correct: true

  # Provision khan dot files
  config.vm.provision "gitconfig", type:"file", source: "~/.gitconfig", destination: ".gitconfig"
  config.vm.provision "gcloud", type:"file", source: "~/.config/gcloud", destination: ".config/gcloud"
  config.vm.provision "arc", type:"file", source: "~/.arcrc", destination: ".arcrc"
  config.vm.provision "khan-dotfiles", type:"shell", privileged: false, :inline => <<END
    ln -s ~/khan/devtools/khan-dotfiles/.bashrc.khan ~/.bashrc.khan
    ln -s ~/khan/devtools/khan-dotfiles/.profile.khan ~/.profile.khan
    ln -s ~/khan/devtools/khan-dotfiles/.bash_profile.khan ~/.bash_profile.khan
END
  # Run setup.sh on first startup
  # TODO(ericbrown): setup.sh assumes too much about where it is running
  config.vm.provision "setup", type:"shell", privileged: false, run: "never", :inline => <<END
    cd ~/khan/devtools/khan-dotfiles
    ./setup.sh
END

end
